import { FaHtml5, FaJs, FaReact } from "react-icons/fa";

const projectsdata = [
  {
    id: 1,
    img: "https://app.aave.com/aaveLogo.svg",
    url: "https://aave.com/",
    github: "https://github.com/aave",
    twitter: "https://twitter.com/aave",
    discord: "https://discord.gg/tNHtcUaT",
    title: "Aave",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet", "loloo"],
    text: "Aave is a non-custodial, open-sourced decentralized liquidity protocol that enables people to supply and borrow crypto assets.",
  },
  {
    id: 2,
    img: "https://scroll-eco-list.netlify.app/logos/Chainge.png",
    url: "https://chainge.finance/",

    twitter: "https://twitter.com/FinanceChainge",

    telegram: "https://t.me/chaingefinance",
    title: "Chainge",
    category: "DeFi",
    mainnet: false,
    labels: ["mainnet"],
    text: "Chainge Finance stands as the most liquid cross-chain aggregated DEX, seamlessly merging liquidity sources across 50+ chains. Chainge also serves as one of the market's main bridge infrastructure providers and accomodates $ETH bridging to Scroll directly from over 25 chains.",
  },
  {
    id: 3,
    img: "../public/images/ankr.png",
    url: "https://www.ankr.com/",

    twitter: "https://twitter.com/ankr",
    discord: "https://discord.gg/ankrofficial",
    telegram: "https://t.me/ankrnetwork",
    title: "Ankr",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Ankr’s globally distributed node infrastructure allows us to build the best possible multi-chain tools as a foundational layer for Web3, DeFi, and the crypto economy.",
  },
  {
    id: 4,
    img: "../public/images/celer.png",
    url: "https://celer.network/",
    github: "https://github.com/celer-network",
    twitter: "https://twitter.com/CelerNetwork",
    discord: "https://discord.gg/UrgSq9s6",
    telegram: "https://t.me/celernetwork",
    title: "Celer Network",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Ankr’s globally distributed node infrastructure allows us to build the best possible multi-chain tools as a foundational layer for Web3, DeFi, and the crypto economy.",
  },
  {
    id: 5,
    img: "../public/images/safe.jpg",
    url: "https://safe.scroll.xyz/",
    github: "https://github.com/safe-global",
    twitter: "https://twitter.com/safe",
    discord: "https://discord.gg/pCAVWd39",

    title: "Safe",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Gnosis Safe is the safety standard of Web3 and the most trusted platform to manage digital assets for individuals and communities.",
  },
  {
    id: 6,
    img: "../public/images/kyberswap.png",
    url: "https://kyberswap.com/",
    github: "https://github.com/john-smilga",
    twitter: "https://twitter.com/KyberNetwork",
    discord: "https://discord.gg/kyberswap",
    telegram: "https://t.me/kybernetwork",
    title: "KyberSwap",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "KyberSwap deploys aggregator, liquidity protocol, cross-chain swaps and will onboard users to Scroll.",
  },
  {
    id: 7,
    img: "../public/images/okx.png",
    url: "https://www.okx.com/tr/web3",

    twitter: "https://twitter.com/OKX",

    title: "OKX Wallet",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "OKX Web3 Wallet is a developer-friendly blockchain wallet, featuring its multi-chain, security, and decentralized aspects.",
  },
  {
    id: 8,
    img: "../public/images/DODO.png",
    url: "https://app.dodoex.io/swap/network/scr/534352-WETH/534352-USDC",
    github: "https://github.com/DODOEX",
    twitter: "https://twitter.com/BreederDodo",
    discord: "https://discord.gg/bM2XHEqg",
    telegram: "https://t.me/dodoex_official",
    title: "DODO",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Decentralized Trading Protocol for Web3, Powered by the Proactive Market Making (PMM) algorithm; aggregator with deep on-chain liquidity.",
  },
  {
    id: 9,
    img: "../public/images/stargate.png",
    url: "https://stargate.finance/",
    github: "https://github.com/stargate-protocol",
    twitter: "https://twitter.com/StargateFinance",
    discord: "https://discord.com/invite/XKbB4um",
    telegram: "https://t.me/joinchat/LEM0ELklmO1kODdh",
    title: "Stargate",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Stargate is a fully composable liquidity transport protocol that lives at the heart of Omnichain DeFi",
  },
  {
    id: 10,
    img: "../public/images/sushi.png",
    url: "https://www.sushi.com/",
    github: "https://github.com/sushiswap",
    twitter: "https://twitter.com/sushiswap",
    discord: "https://discord.gg/rXpFtFKf",

    title: "Sushi",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Sushi: the tasty DeFi platform serving up cross-chain swapping and liquidity incentives. Come take a bite and join the decentralized feast!",
  },
  {
    id: 11,
    img: "../public/images/orbiter.png",
    url: "https://www.orbiter.finance/",
    github: "https://github.com/Orbiter-Finance",
    twitter: "https://twitter.com/Orbiter_Finance",
    discord: "https://discord.gg/yyjGKm2e",

    title: "Orbiter Finance",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Orbiter Finance is a decentralized cross-rollup Layer 2 bridge with a contract only on the destination side.",
  },
  {
    id: 12,
    img: "../public/images/graph.png",
    url: "https://thegraph.com/en/",
    github: "https://github.com/graphprotocol",
    twitter: "https://twitter.com/graphprotocol",
    discord: "https://discord.gg/EPyXtTF4",
    telegram: "https://t.me/graphprotocol",
    title: "The Graph",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "The Graph is a web3 protocol for organizing and accessing blockchain data",
  },
  {
    id: 13,
    img: "../public/images/openocean.png",
    url: "https://openocean.finance/",
    github: "https://github.com/openocean-finance/",
    twitter: "https://twitter.com/OpenOceanGlobal",
    telegram: "https://t.me/OOFinance",
    title: "OpenOcean",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "OpenOcean is the leading DEX aggregator across 30+ networks and integrated 1000+ deep liquidity sources. With its dynamic intelligent routing algorithm, OpenOcean brings the best swap returns for on-chain crypto trading on Scroll",
  },
  {
    id: 14,
    img: "../public/images/secondlive.jpg",
    url: "https://secondlive.world/",
    github: "https://github.com/SecondLive23",
    twitter: "hhttps://twitter.com/SecondLiveReal",
    discord: "https://discord.com/invite/secondlive",
    telegram: "https://t.me/SecondLiveCommunity",
    title: "SecondLive",
    category: "Social",
    mainnet: true,
    labels: ["mainnet"],
    text: "AI-driven Open Metaverse",
  },
  {
    id: 15,
    img: "../public/images/izumi.png",
    url: "https://izumi.finance/home",
    github: "https://github.com/IzumiFinance/",
    twitter: "https://twitter.com/izumi_Finance",
    discord: "https://discord.com/invite/izumifinance",
    telegram: "https://t.me/izumifinance",
    title: "Izumi Finance",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Liquidity Redefined - A multi-chain DeFi protocol providing One-Stop Liquidity as a Service (LaaS).",
  },
  {
    id: 16,
    img: "../public/images/versa.svg",
    url: "https://versawallet.io/",
    github: "https://github.com/john-smilga",
    twitter: "https://twitter.com/versawallet",
    discord: "https://discord.com/invite/gGkcce2mRM",
    telegram: "https://t.me/versawallet",
    title: "Versa Wallet",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "Your Crypto Co-pilot.",
  },
  {
    id: 17,
    img: "../public/images/Blocto.png",
    url: "https://blocto.io/",
    github: "https://github.com/blocto",
    twitter: "https://twitter.com/BloctoApp",
    discord: "https://discord.com/invite/QRZTr6yHmY",

    title: "Blocto",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "The Ultimate Account Abstraction Wallet for Secure, Efficient, and Cost-Effective Multi-Chain Transactions",
  },
  {
    id: 18,
    img: "../public/images/AlienSwap.png",
    url: "https://alienswap.xyz/",

    twitter: "https://twitter.com/AlienSwap_NFT",
    discord: "https://discord.com/invite/6SzkW9hNRa",
    telegram: "https://t.me/alienswap_official",
    title: "AlienSwap",
    category: "NFT",
    mainnet: true,
    labels: ["mainnet"],
    text: "AlienSwap is a multi-chain NFT marketplace and aggregator aimed to build the leading trading layer for the community, now we have integrated Scroll not only with the marketplace, but also our ... ",
  },
  {
    id: 19,
    img: "../public/images/SynFutures.png",
    url: "https://www.synfutures.com/",

    twitter: "https://twitter.com/SynFuturesDefi",
    discord: "https://discord.com/invite/synfutures",
    telegram: "https://t.me/synfutures_Defi",
    title: "SynFutures",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "List and trade any futures contracts based on popular cryptocurrencies, altcoins, indices, NFTs and real-world assets - you name it!.",
  },
  {
    id: 20,
    img: "../public/images/zklink.png",
    url: "https://zk.link/",
    github: "https://github.com/zkLinkProtocol",
    twitter: "https://twitter.com/zkLink_Official",
    discord: "https://discord.com/invite/zklink",
    telegram: "https://t.me/zkLinkorg",
    title: "zkLink",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "zkLink is a unified multi-chain zkRollup L2 network, empowering the next-gen DeFi and NFT trading solutions..",
  },
  {
    id: 21,
    img: "../public/images/symbiosis.png",
    url: "https://symbiosis.finance/",
    github: "https://github.com/symbiosis-finance",
    twitter: "https://twitter.com/symbiosis_fi",
    discord: "https://discord.com/invite/YHgDSJ42eG",
    telegram: "https://t.me/symbiosis_finance",
    title: "Symbiosis",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Symbiosis is a multi-chain liquidity protocol. Our know-how: a single click any-to-any token swaps regardless of the network, EVM and non-EVM are supported.",
  },
  {
    id: 22,
    img: "../public/images/rhino.fi.png",
    url: "https://rhino.fi/",

    twitter: "https://twitter.com/rhinofi",
    discord: "https://discord.com/invite/26sXx2KAhy",

    title: "rhino.fi",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "The worlds best multichain DeFi aggregator, from one self-custodial layer 2 wallet. Trade. Swap. Invest. Earn. ",
  },
  {
    id: 23,
    img: "../public/images/Pyth.svg",
    url: "https://pyth.network/",
    github: "https://github.com/pyth-network",
    twitter: "https://twitter.com/PythNetwork",
    discord: "https://discord.com/invite/PythNetwork",
    telegram: "https://t.me/Pyth_Network",
    title: "Pyth Network",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Pyth is a first-party financial oracle continuously providing real-world data on-chain in a tamper-resistant, decentralized, and self-sustainable way",
  },
  {
    id: 24,
    img: "../public/images/Covalent.png",
    url: "https://www.covalenthq.com/",
    github: "https://github.com/covalenthq/",
    twitter: "https://twitter.com/Covalent_HQ",
    discord: "https://discord.com/invite/VHgmzB9973",
    telegram: "https://t.me/CovalentHQ",
    title: "Covalent",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Covalent provides the industry-leading Unified API bringing visibility to billions of Web3 data points. Developers use Covalent to build exciting multi-chain applications using data from 26+ blockchains.",
  },
  {
    id: 25,
    img: "../public/images/keystone.png",
    url: "https://keyst.one/",
    github: "https://github.com/KeystoneHQ",
    twitter: "https://twitter.com/KeystoneWallet",
    discord: "https://discord.com/invite/gpfaESrxu2",
    telegram: "https://t.me/KeystoneWallet",
    title: "Keystone",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "Keystone is a 100% air-gapped QR code hardware wallet. The wallet is designed to maximize attack cost, minimize trust, prevent potential human error, avoid single-point-of-failures and boost interoperability with maximized compatibility to most of top software wallets.",
  },
  {
    id: 26,
    img: "../public/images/pocket.png",
    url: "https://www.pokt.network/",
    github: "https://github.com/pokt-network/pocket",
    twitter: "https://twitter.com/POKTnetwork",
    discord: "https://discord.com/invite/pokt",
    telegram: "https://t.me/POKTnetwork",
    title: "Pocket Network",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Pocket Network provides RPC access to Ethereum, Polygon, and dozens of multichains. Everything from mainnets to mainnets to any open-source interface. ",
  },
  {
    id: 27,
    img: "../public/images/SyncSwap.png",
    url: "https://syncswap.xyz/intro",
    github: "https://github.com/syncswap",
    twitter: "https://twitter.com/syncswap",
    discord: "https://discord.com/invite/syncswap",

    title: "SyncSwap",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "SyncSwap is a seamless DEX on ETH ZK Rollups, brings easy-to-use and low-cost DeFi to everyone with full Ethereum security powered by zk technology.",
  },
  {
    id: 28,
    img: "../public/images/Particle.png",
    url: "https://particle.network/",
    github: "https://github.com/Particle-Network",
    twitter: "https://twitter.com/ParticleNtwrk",
    discord: "https://discord.com/invite/2y44qr6CR2",

    title: "Particle Network",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Particle Network's Smart WaaS empowers Scroll devs w: • Seamless onboarding: Web2 logins & full-stack account abstraction. • Faster development: Create smart accounts & UserOperations with ease. • Advanced features: Gasless transactions, batching, & account programmability.",
  },
  {
    id: 29,
    img: "../public/images/FoxWallet.png",
    url: "https://foxwallet.com/",
    github: "https://github.com/foxwallet",
    twitter: "https://twitter.com/FoxWallet",
    discord: "https://discord.com/invite/foxwallet",
    telegram: "https://t.me/FoxWallet_EN",
    title: "FoxWallet",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "FoxWallet is a safe and easy-to-use decentralized audited wallet, dedicated to creating an entrance and connection to the Web3 world. ",
  },
  {
    id: 30,
    img: "../public/images/Mathwallet.png",
    url: "https://mathwallet.org/en-us/",
    github: "https://github.com/mathwallet",
    twitter: "https://twitter.com/Mathwallet",
    discord: "https://discord.com/invite/gXSfnk5eP5",
    telegram: "https://t.me/mathwalletnews",
    title: "Math Wallet",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "MathWallet is the Multichain Wallet for Web3 that enables token storage of 150+chains, supports cross-chain token bridges and multi-chain dApp store. We support Scroll mainnet, mainnet and ecosystem. Help users get in Scroll easily. ",
  },
  {
    id: 31,
    img: "../public/images/Atem.png",
    url: "https://www.atem.io/",

    twitter: "https://twitter.com/atem_network",
    discord: "https://discord.com/invite/atem",
    telegram: "https://t.me/AtemNetworkOfficial",
    title: "Atem Network",
    category: "Social",
    mainnet: true,
    labels: ["mainnet"],
    text: "Atem Network is a decentralized content creation protocol, we aim at helping creators to tokenize their content and build web3 native communities. ",
  },
  {
    id: 32,
    img: "../public/images/Router.png",
    url: "https://www.routerprotocol.com/",
    github: "https://github.com/router-protocol",
    twitter: "https://twitter.com/routerprotocol?t=Jab_H522Y2fB6uM60Pn6zA",
    discord: "https://discord.com/invite/rKf9UYMNWC",
    telegram: "https://t.me/routerprotocol",
    title: "Router Protocol",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Router Protocol is a pioneering cross-chain solution that enables secure and efficient communication between blockchain networks.",
  },
  {
    id: 33,
    img: "../public/images/UniPass.jpg",
    url: "https://unipass.id/",
    github: "https://github.com/john-smilga",
    twitter: "https://twitter.com/UniPassWallet",
    discord: "https://discord.com/invite/aeqXrCHzrV",
    telegram: "https://t.me/UniPassWalletApp",
    title: "UniPass",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "UniPass is a non-custodial smart contract wallet that provides a seedless and gasless user experience.",
  },
  {
    id: 34,
    img: "../public/images/Bware.png",
    url: "https://bwarelabs.com/",
    github: "https://github.com/bwarelabs",
    twitter: "https://twitter.com/BwareLabs",
    discord: "https://discord.com/invite/bwarelabs",
    telegram: "https://t.me/bwareLabs",
    title: "Bware Labs",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Bware Labs is an infrastructure company aiming to power Web3 development and become the next public cloud for blockchain products.",
  },
  {
    id: 35,
    img: "../public/images/Espresso.png",
    url: "https://www.espressosys.com/",
    github: "https://github.com/espressosystems/",
    twitter: "https://twitter.com/EspressoSys",
    discord: "https://discord.com/invite/YHZPk5dbcq",

    title: "Espresso Systems",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Espresso Systems builds tools and infrastructure that create more safe, open, and performant options for interacting and transacting on-chain.",
  },
  {
    id: 36,
    img: "../public/images/Satori.png",
    url: "https://scroll.satori.finance/trade/",

    twitter: "https://twitter.com/SatoriFinance",
    discord: "https://discord.com/invite/GXdRnBVfUf",

    title: "Satori Finance",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "We are the leading perpetuals platform for zkEVM chains. We are currently on Scroll, Linea, zkSync and Polygon zkEVM.",
  },
  {
    id: 37,
    img: "../public/images/OkLink.png",
    url: "https://www.oklink.com/tr/scroll",

    title: "OkLink",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "OKLink is a leading blockchain service provider, including blockchain data analysis, on-chain information integration and AML solutions. ",
  },
  {
    id: 38,
    img: "../public/images/BlockPI.png",
    url: "https://blockpi.io/",

    twitter: "https://twitter.com/RealBlockPI",
    discord: "https://discord.com/invite/xTvGVrGVZv",
    telegram: "https://t.me/blockpidaily",
    title: "BlockPI Network",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "BlockPI Network is a distributed multi-chain acceleration layer, engaging in an accessible and decentralized Web3 environment. The BlockPI provides efficient, reliable and high performance globally distributed API service for Web3 builders.",
  },
  {
    id: 39,
    img: "../public/images/RedStone.png",
    url: "https://redstone.finance/",
    github: "https://github.com/redstone-finance",
    twitter: "https://twitter.com/redstone_defi",
    discord: "https://discord.com/invite/PVxBZKFr46",
    telegram: "https://t.me/redstonefinance/",
    title: "RedStone",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "RedStone is a data ecosystem that delivers frequently updated, reliable and diverse data for your dApp and smart contracts.",
  },
  {
    id: 40,
    img: "../public/images/Witnet.png",
    url: "https://witnet.io//",
    github: "https://github.com/witnet",
    twitter: "https://twitter.com/witnet_io",
    discord: "https://discord.com/invite/witnet",
    telegram: "https://t.me/witnetio",
    title: "Witnet",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Layer one multichain decentralized oracle network powered by the $WIT coin. ",
  },
  {
    id: 41,
    img: "../public/images/OpenBlock.png",
    url: "https://openblock.com/",

    twitter: "https://twitter.com/OpenBlockWallet",
    discord: "https://discord.com/invite/EhsKYbvtJx",

    title: "OpenBlock",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "OpenBlock provides a 2C wallet solution by utilizing MPC protocol and a super-app design principle that is more secure, accessible, and powerful. ",
  },
  {
    id: 42,
    img: "../public/images/Cubic.png",
    url: "https://www.cubicgames.xyz/home",

    twitter: "https://twitter.com/cubicgamesxyz",
    discord: "https://discord.com/invite/cubicgames",
    telegram: "https://t.me/cubicgamesxyz",
    title: "Cubic",
    category: "Gaming",
    mainnet: true,
    labels: ["mainnet"],
    text: "Cubic is a gaming infrastructure on Scroll, onboarding millions of users and game studios to the Web3 gaming era. ",
  },
  {
    id: 43,
    img: "../public/images/Etherspot.png",
    url: "https://etherspot.io/",
    github: "https://github.com/etherspot/",
    twitter: "https://twitter.com/etherspot",
    discord: "https://discord.com/invite/GAkYj6m5Uh",
    telegram: "https://t.me/etherspot",
    title: "Etherspot",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Account Abstraction SDK that simplifies complex blockchain operations and enables easy onboarding of new users for a frictionless Web3 experience",
  },
  {
    id: 44,
    img: "../public/images/Poolshark.png",
    url: "https://www.poolshark.fi//",

    twitter: "https://twitter.com/poolsharklabs",
    discord: "https://discord.com/invite/HJhrD9sZ6K",

    title: "Poolshark",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Poolshark is an open-source AMM protocol that makes it easy for users to catch directional moves from the comfort of a liquidity pool. ",
  },
  {
    id: 45,
    img: "../public/images/Owlto.png",
    url: "https://owlto.finance/",
    github: "https://github.com/owlto-finance/",
    twitter: "https://twitter.com/Owlto_Finance",
    discord: "https://discord.gg/owlto",

    title: "Owlto Finance",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "The Decentralized Cross-Rollup Bridge Focused On Layer 2 ",
  },
  {
    id: 46,
    img: "../public/images/Sakaba.png",
    url: "https://sakaba.xyz/",

    twitter: "https://twitter.com/SAKABA_xyz",
    discord: "https://discord.com/invite/6cFmEb78k7",

    title: "Sakaba",
    category: "Gaming",
    mainnet: true,
    labels: ["mainnet"],
    text: "Next-gen interconnected blockchain gaming hub which sets new standard of gaming via our cross-game DID, launchpad and game player discovery system",
  },
  {
    id: 47,
    img: "../public/images/Kingdoms.jpeg",
    url: "https://www.scrollkingdoms.com/",

    twitter: "https://twitter.com/ScrollKingdoms",

    title: "Scroll Kingdoms",
    category: "Community",
    mainnet: true,
    labels: ["mainnet"],
    text: "Scroll Kingdoms is a cross chain free to play MMORPG. Users can customize their characters by changing their name, equipping items",
  },
  {
    id: 48,
    img: "../public/images/OmniKingdoms.png",
    url: "https://www.omnikingdoms.io/",

    twitter: "https://twitter.com/OmniKingdoms",
    discord: "https://discord.com/invite/PzRnWxa8ks",

    title: "OmniKingdoms",
    category: "Community",
    mainnet: true,
    labels: ["mainnet"],
    text: "OmniKingdoms is an on-chain MMORPG that focuses on state transitions. Players can join the community and earn rewards for questing, battling, crafting and much more. We aim to integrate the newest gaming mechanics and other projects. ",
  },
  {
    id: 49,
    img: "../public/images/Pheasant.png",
    url: "https://pheasant.network/",
    github: "https://github.com/Pheasant-Network",
    twitter: "https://twitter.com/PheasantNetwork",
    discord: "https://discord.com/invite/pRYSEUVERT",

    title: "Pheasant Network",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Pheasant Network is an optimistic bridge between Layer 1 and Layer 2. ",
  },
  {
    id: 50,
    img: "../public/images/Unifra.png",
    url: "https://unifra.io/",

    twitter: "https://twitter.com/UnifraPlatform",
    discord: "https://discord.com/invite/6fxayYKa3w",

    title: "Unifra",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Open infrastructure for everyone. Unifra provides open, reliable infrastructure service for all web3 developers ",
  },
  {
    id: 51,
    img: "../public/images/Cog.png",
    url: "https://www.cog.finance/",

    twitter: "https://twitter.com/CogFinance",
    discord: "https://discord.com/invite/hgRbqu7TG3",

    title: "Cog Finance",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Cog is a new isolated lending protocol that aims to maximize both decentralization and capital efficiency that many existing solutions are currently lacking. ",
  },
  {
    id: 52,
    img: "../public/images/Scry.png",
    url: "https://scry.finance/",

    twitter: "https://twitter.com/scryprotocol",

    title: "Scry Protocol",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Scry is an open source, permissionless and robust framework for Oracle deployment. ",
  },
  {
    id: 53,
    img: "../public/images/Loanshark.png",
    url: "https://loanshark.tech/",
    github: "https://github.com/loansharktechteam",
    twitter: "https://twitter.com/loansharktech",
    discord: "https://discord.com/invite/tbSEWQYMKV",

    title: "Loanshark",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Loanshark is building a lending protocol with a risk isolated lending pool structure that offers superior capital efficiency and better UX. ",
  },
  {
    id: 54,
    img: "../public/images/gas.zip.png",
    url: "https://www.gas.zip/",

    twitter: "https://twitter.com/gasdotzip",
    discord: "https://discord.com/invite/gasdotzip",

    title: "Gas.zip",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Gas.zip is the fastest one-stop gas refuel bridge for over 140+ chains. Scroll is one of the most heavily bridged destinations and has been for months. ",
  },
  {
    id: 55,
    img: "../public/images/ZKSynth.png",
    url: "https://zksynth.com/",

    twitter: "https://twitter.com/zkSynth",
    discord: "https://discord.com/invite/DcVSvsdDHy",

    title: "ZKSynth",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "ZKSynth is a Decentralized Synthetics Protocol on Scroll, enabling 500+ real-world assets in DeFi with - Isolated Synthetic Pools - Slippage Free Swaps - Perpetuals, Options, Structured Assets such as Indices, Leveraged Tokens, CDOs, etc ",
  },
  {
    id: 56,
    img: "../public/images/ChatNPC.svg",
    url: "https://chatnpc.gg/",

    twitter: "https://twitter.com/chatnpcai",

    title: "ChatNPC",
    category: "Gaming",
    mainnet: true,
    labels: ["mainnet"],
    text: "Test your negotiation skills against AI-powered fictional crypto figures. ",
  },
  {
    id: 57,
    img: "../public/images/Splatter.png",
    url: "https://splatterprotocol.xyz/",

    title: "Splatter Protocol",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "An innovative, community-driven DEX protocol featuring on-chain Dao mechanics, ensuring seamless smart contract updates and upgradability ",
  },
  {
    id: 58,
    img: "../public/images/Zeron.png",
    url: "https://scroll.zeron.work/payments",
    github: "https://github.com/Zeron-Protocol",
    twitter: "https://twitter.com/Zeron_Protocol",
    discord: "https://discord.com/invite/k2mryMc6KP",

    title: "Zeron Protocol",
    category: "Social",
    mainnet: true,
    labels: ["mainnet"],
    text: "Zeron Protocol is a decentralized employment protocol that utilizes trustless Self-Automated Smart Contracts to allow users to Escrows and Salary Payments using crypto and adopt a decentralized arbitration tribunal to resolve subjective disputes. ",
  },
  {
    id: 58,
    img: "../public/images/Privy.jpg",
    url: "https://www.privy.io/",
    github: "https://github.com/privy-io",
    twitter: "https://twitter.com/privy_io",

    title: "Privy",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "One simple library to add beautiful authentication flows and powerful embedded wallets to your app. ",
  },
  {
    id: 59,
    img: "../public/images/Innovaz.png",
    url: "https://innovaz.io/",

    twitter: "https://twitter.com/Innovaz_io",
    discord: "https://discord.com/invite/qzqXgxD32f",

    title: "Innovaz",
    category: "Tooling",
    mainnet: true,
    labels: ["mainnet"],
    text: "Innovaz empowers creators to launch customized NFT marketplaces effortlessly and cost-free. ",
  },
  {
    id: 60,
    img: "../public/images/Meson.svg",
    url: "https://meson.fi/",
    github: "https://github.com/MesonFi",
    twitter: "https://twitter.com/mesonfi",
    discord: "https://discord.com/invite/meson",
    telegram: "https://t.me/mesonfi",

    title: "Meson",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Meson is a leading unified stablecoin bridging protocol that provides a seamless cross-chain experience for ETH and stablecoins across over 30 high-performance public chains and layer-2/3 solutions ",
  },
  {
    id: 61,
    img: "../public/images/zkMarkets.png",
    url: "https://www.zkmarkets.com/scroll-mainnet",

    twitter: "https://twitter.com/zkmarkets",
    discord: "https://discord.com/invite/zkmarkets",

    title: "zkMarkets",
    category: "Tooling",
    mainnet: true,
    labels: ["mainnet"],
    text: "A lightning-fast NFT marketplace, packed with professional tools for every occasion! ",
  },
  {
    id: 62,
    img: "../public/images/spacefi.png",
    url: "https://spacefi.io/",
    github: "https://twitter.com/spacefi_io",
    twitter: "https://twitter.com/spacefi_io",
    discord: "https://discord.com/invite/nezjCa5j8r",

    title: "SpaceFi",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "SpaceFi is the DeFi hub on zk Rollups with DEX+NFT+Spacebase+Launchpad, exploring the Layer2 ecosystem. ",
  },
  {
    id: 63,
    img: "../public/images/PADO.png",
    url: "https://www.padolabs.org/",
    github: "https://github.com/PADO-labs",
    twitter: "https://twitter.com/padolabs",
    discord: "https://discord.com/invite/fYGHnFPB4S",

    title: "PADO Labs",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "PADO Labs is a cryptography technology provider focusing on reconstructing a new paradigm for credit protocols. ",
  },
  {
    id: 64,
    img: "../public/images/Onto.png",
    url: "https://onto.app/",
    github: "https://github.com/ONTO-Data-Wallet",
    twitter: "https://twitter.com/ONTOWallet",

    telegram: "https://t.me/ONTOWallet",
    title: "Onto Wallet",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "An all-in-one solution for Web3 to manage identity, data, and assets, with 1M+ users, 1,000+ supported dApps across 60+ blockchains ",
  },
  {
    id: 65,
    img: "../public/images/NFTs2Me.png",
    url: "https://nfts2me.com/",

    twitter: "https://twitter.com/nfts2me",
    discord: "https://discord.com/invite/Usmgxj2Msk",
    telegram: "https://t.me/nfts2me",
    title: "NFTs2Me",
    category: "NFT",
    mainnet: true,
    labels: ["mainnet"],
    text: "NFTs2Me is a multichain user-friendly comprehensive platform to create, deploy and manage your NFT collection, 100% free with advanced functionalities ",
  },
  {
    id: 66,
    img: "../public/images/NerveNetwork.png",
    url: "https://nerve.network/",
    github: "https://github.com/NerveNetwork",
    twitter: "https://twitter.com/nerve_network",
    discord: "https://discord.com/invite/PBkHeD7",
    telegram: "https://t.me/NerveNetwork",
    title: "NerveNetwork",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "NerveNetwork is an asset relay network connecting multiple blockchains. ",
  },
  {
    id: 67,
    img: "../public/images/joy.png",
    url: "https://joy.id/",
    github: "https://github.com/nervina-labs",
    twitter: "https://twitter.com/joy_protocol",
    discord: "https://discord.com/invite/77MyakRKVB",

    title: "JoyID",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "JoyID is a multi-chain, cross-platform, passwordless, and mnemonic-free wallet solution based on FIDO Webauthn protocol and Nervos CKB.",
  },
  {
    id: 68,
    img: "../public/images/Skydrome.png",
    url: "https://skydrome.finance/",
    github: "https://github.com/SkyDromeFinance",
    twitter: "https://twitter.com/skydrome",
    discord: "https://discord.com/invite/ZbE69CARXm",

    title: "Skydrome",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Skydrome is the central liquidity hub on Scroll, with a full commitment to being community and developer-owned, making it the most comprehensive v3.3 ",
  },
  {
    id: 69,
    img: "../public/images/layerbank.png",
    url: "https://scroll.layerbank.finance/bank",
    github: "https://github.com/layerbank/contracts",
    twitter: "https://twitter.com/LayerBankFi",
    discord: "https://discord.com/invite/g8eNuudNxe",

    title: "Layer Bank",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "LayerBank is a lending protocol that provides a universal, permissionless banking solution for all EVM rollups, serving as their liquidity hub. ",
  },
  {
    id: 70,
    img: "../public/images/Bitget.png",
    url: "https://web3.bitget.com/en/",
    github: "https://github.com/bitkeepwallet/download",
    twitter: "https://twitter.com/BitgetWallet",
    discord: "https://discord.com/invite/bitget-wallet",

    title: "Bitget Wallet",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "Faster Trading, Better Assets Bitget Wallet — Your Web3 Trading Wallet of the Future ",
  },
  {
    id: 71,
    img: "../public/images/1RPC.png",
    url: "https://www.1rpc.io/",
    github: "https://github.com/automata-network",
    twitter: "https://twitter.com/1rpc_",
    discord: "https://discord.com/invite/automata",
    telegram: "https://t.me/ata_network",

    title: "1RPC",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "The first and only on-chain attested privacy preserving RPC, with a track record of protecting 10 billion requests. ",
  },
  {
    id: 72,
    img: "../public/images/Blast.png",
    url: "https://blastapi.io/",
    github: "https://github.com/bwarelabs",
    twitter: "https://twitter.com/BlastAPI",
    discord: "https://discord.com/invite/bwarelabs",
    telegram: "https://t.me/bwareLabs",
    title: "Blast API(Bware Labs)",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "BLAST is a next-gen, blockchain API platform, featuring the fastest blockchain access to an ever-growing number of blockchains in the Web3 space ",
  },
  {
    id: 73,
    img: "../public/images/Okto.png",
    url: "https://okto.tech/",

    twitter: "https://twitter.com/okto_web3",
    discord: "https://discord.com/invite/Y9ZJ7vrpSE",
    telegram: "https://t.me/OktoOfficial",

    title: "Okto",
    category: "Wallet",
    mainnet: true,
    labels: ["mainnet"],
    text: "Okto is a web3 super app designed to redefine your web3 user experience across the multi-chain ecosystem. Okto stands out by eliminating the complexities and common errors DeFi users, investors, and traders often encounter, offering a seamless and intuitive interface that caters to both beginners and seasoned DeFi users. Key components of the Okto App include Okto bridge, Swap, Gas Station Network, in-app Futures, NFT viewing and transfer, multi-chain support and fiat on-and-off-ramp. ",
  },
  {
    id: 74,
    img: "../public/images/Irys.jpg",
    url: "https://irys.xyz/",
    github: "https://github.com/Irys-xyz",
    twitter: "https://twitter.com/irys_xyz",
    discord: "https://discord.com/invite/sGEP5qqTQK",
    telegram: "https://t.me/irys_xyz",
    title: "Irys",
    category: "Tooling",
    mainnet: true,
    labels: ["mainnet"],
    text: "Irys is a provenance layer that enables users to limitlessly upload and sequence data while precisely attributing its origin. All data that is uploaded with Irys is stored permanently onchain. Now that Irys integrated ETH on Scroll, any user or application can pay for data uploads seamlessly; for example an NFT minting platform can sign with their wallet and pay for the NFT metadata + image to be stored permanently with Irys via ETH-Scroll. ",
  },
  {
    id: 75,
    img: "../public/images/Kelpdao.jpg",
    url: "https://www.kelpdao.xyz/restake/",

    twitter: "https://twitter.com/KelpDAO",
    discord: "https://discord.gg/YzdXPTVP",
    telegram: "https://t.me/KelpDAOxyz",
    title: "Kelp DAO",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Kelp brings native restaking to Scroll. Scroll users can now get the benefits of restaking rewards from the mainnet while enjoying the low gas fees and faster transaction speed of Scroll. We have also integrated with Ambient, Layerbank to provide utility for rsETH (Liquid token) via various DeFi opportunities. ",
  },
  {
    id: 76,
    img: "../public/images/Tranchess.png",
    url: "https://tranchess.com/",
    github: "https://github.com/tranchess",
    twitter: "https://twitter.com/tranchess",
    discord: "https://discord.com/invite/tKxAq78VBr",
    telegram: "https://t.me/tranchess",
    title: "Tranchess",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "- Structured liquid staking (with stone and other LST in the future) - DeFi product differentiation vs existing products/protocols on any other chain - 1st of its kind product on Tranchess: turP and staY - Attracting TVL to Scroll via innovative products ",
  },
  {
    id: 77,
    img: "../public/images/Cryptorank.jpg",
    url: "https://app.cryptorank.io/",

    twitter: "https://twitter.com/CryptoRank_io",

    telegram: "https://t.me/CryptoRankEn",
    title: "Cryptorank",
    category: "NFT",
    mainnet: true,
    labels: ["mainnet"],
    text: "app.cryptorank.io ",
  },
  {
    id: 78,
    img: "../public/images/Bungee.jpg",
    url: "https://www.bungee.exchange/",

    twitter: "https://twitter.com/BungeeExchange",

    title: "Bungee",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Socket is an interoperability protocol for secure & efficient data and asset transfers across chains. Socket is not a bridge, or a cross chain app - it is an infrastructure that allows developers to build these things easily. Developers can use Socket to build apps with interoperability as a core part of app infrastructure. ",
  },
  {
    id: 79,
    img: "../public/images/tanX.jpg",
    url: "https://tanx.fi/",

    twitter: "https://twitter.com/tanXfinance",
    discord: "https://discord.com/invite/FXkCxUdrMd",
    title: "tanX",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Reliable, self custodial and high performance liquidity network for traders, institutions and exchanges. ",
  },
  {
    id: 80,
    img: "../public/images/Stakestone.jpg",
    url: "https://stakestone.io/",

    twitter: "https://twitter.com/Stake_Stone",
    discord: "https://discord.com/invite/cswURCh8Nx",
    telegram: "https://t.me/StakeStone",
    title: "Stake Stone",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Omnichain Liquidity Infrastructure ",
  },
  {
    id: 81,
    img: "../public/images/peak.jpg",
    url: "https://peakid.domains/",

    twitter: "https://twitter.com/Peak_id",
    discord: "https://discord.com/invite/sUAbXH8Gaq",

    title: "PeakID",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "PeakID - Your portal to the Scroll Universe, simplifying Web3 identity, payment, and defi experience. 🔸ID Marketplace and Leaderboard 🔸SocialFi extension 🔸Scoring mechanism with ONE-ID 🔸Payment and Defi Narratives ",
  },
  {
    id: 82,
    img: "../public/images/Rango.jpg",
    url: "https://app.rango.exchange/",

    twitter: "https://twitter.com/RangoExchange",
    discord: "https://discord.com/invite/q3EngGyTrZ",
    telegram: "https://t.me/rangoexchange",
    title: "Rango Exchange",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Rango is the ultimate cross-chain DEX and bridge aggregator built for the dynamic crypto industry. It supports different blockchains (+60 chains) such as EVM-based, Cosmos-based, ZK-rollups, Solana, and UTXOs. As a leading DEX platform, it bridges all around crypto by simply allowing users to swap assets from any blockchain for any other assets and find the fastest, cheapest, and most secure route. ",
  },
  {
    id: 83,
    img: "../public/images/Hippo.jpg",
    url: "https://hipposwap.finance/",

    twitter: "https://twitter.com/Hippo_Swap",
    discord: "https://discord.com/invite/GmhfBmhfJ8",
    telegram: "https://t.me/hippo_scroll",
    title: "Hippo Swap",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Hippo Swap stands out as a leading DEX Aggregator and a Layer 2 DEX offering swift, secure, and straightforward trading at the most favorable rates on Scroll. Our DEX specializes in concentrated liquidity, allowing users to determine liquidity within a set price scope, thus optimizing trader efficiency and reducing slippage ",
  },
  {
    id: 84,
    img: "../public/images/Web3event.jpg",
    url: "https://www.web3event.org/explore/events",

    twitter: "https://twitter.com/Web3eventorg",

    telegram: "https://t.me/web3event",
    title: "Web3event",
    category: "Community",
    mainnet: true,
    labels: ["mainnet"],
    text: "Web3event is the world's largest Web3 event aggregation platform, with over 30,000 global users. During #Devconnect in November 2023, it received an official recommendation from the Ethereum Foundation, making Web3event the best brand promotion partner for Web3 projects. Right now we are building Events Pass and an offline Check-in Rewards system, so it can be easy to onboarding real-world users to Web3 world. Web3event brings Scroll Eco events to the global community and onboarding Real Users to Scroll Eco Projects. ",
  },
  {
    id: 85,
    img: "../public/images/Lido.jpg",
    url: "https://lido.fi/",
    github: "https://github.com/lidofinance",
    twitter: "https://twitter.com/LidoFinance",
    discord: "https://discord.com/invite/lido",
    telegram: "https://t.me/lidofinance",
    title: "Lido",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Lido is the name of a family of open-source peer-to-system software tools deployed and functioning on the Ethereum, Solana, and Polygon blockchain networks. The software enables users to mint transferable utility tokens, which receive rewards linked to the related validation activities of writing data to the blockchain, while the tokens can be used in other on-chain activities. ",
  },
  {
    id: 86,
    img: "../public/images/VIP3.jpg",
    url: "https://dapp.vip3.io/",

    twitter: "https://twitter.com/web3vip",
    discord: "https://discord.com/invite/DyZtSg6vFN",
    telegram: "https://t.me/+Ate9I03seWhlNTBl",
    title: "VIP3",
    category: "Community",
    mainnet: true,
    labels: ["mainnet"],
    text: "VIP3 is the first web3 CASHBACK platform, giving users cashback over trading fees, gas and other fees on 70 dapps ",
  },
  {
    id: 87,
    img: "../public/images/TokenTable.jpg",
    url: "https://www.tokentable.xyz/",

    twitter: "https://twitter.com/tokentable",

    title: "TokenTable",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "TokenTable is a token management tool that helps startups manage their airdrops, token unlocks and vesting. ",
  },
  {
    id: 88,
    img: "../public/images/Xwand.jpg",
    url: "https://xwand.xyz/",

    twitter: "https://twitter.com/XWand_Scroll",

    title: "Xwand",
    category: "Community",
    mainnet: true,
    labels: ["mainnet"],
    text: "Xwand : The first fair-launch social Token marketplace building on Scroll. Xwand aims to redefine fair launch and social tokens, providing a brand new way for individuals and communities to freely create and trade their own digital assets in the Web3 era. ",
  },
  {
    id: 89,
    img: "../public/images/",
    url: "https://www.zprotocol.xyz/",

    twitter: "https://twitter.com/zprotocolxyz",
    discord: "https://discord.com/invite/zprotocolxyz",

    title: "Z Protocol",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Yield farming has become a popular concept in the decentralized finance (DeFi) space, offering investors an opportunity to earn passive income by lending or staking their digital assets. Z Protocol offers a set of tools essential to a growing decentralized ecosystem. Our goal is to create a synergy between the projects that are currently developing on Scroll, establishing trusted partnerships for our community and the entire Scroll ecosystem. ",
  },
  {
    id: 90,
    img: "../public/images/nitro.png",
    url: "https://app.routernitro.com/swap",
    github: "https://github.com/router-protocol",
    twitter: "https://twitter.com/routerprotocol",
    discord: "https://discord.com/invite/rKf9UYMNWC",
    telegram: "https://t.me/routerprotocol",
    title: "Nitro (by Router Protocol)",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Nitro (Powered by Router Protocol) is a cross-chain liquidity bridge and swap engine Using Nitro you can effortlessly move assets like USDC and ETH from various ecosystems like Tron, Polygon, Arbitrum, Ethereum, etc to Scroll and vice-versa Nitro is gas efficient, pocket friendly, and blazing fast! ",
  },
  {
    id: 91,
    img: "../public/images/TokenSight.jpg",
    url: "https://www.tokensight.io/",
    github: "https://github.com/john-smilga",
    twitter: "https://twitter.com/TokenSight_Io",
    discord: "https://discord.com/invite/7snHpgZQtd",
    telegram:
      "https://t.me/TokenSightCHAT?utm_medium=social&utm_source=linktree&utm_campaign=telegram+chat",
    title: "TokenSight",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "TokenSight is an automated DEX Trading Platform built to simplify and enhance crypto trading. We offer different types of trade orders, token sniping, copy trading and much more. Our platform is intuitive and secure as we have embedded Self-Custodial wallets which can be used to trade on all chains. The value TokenSight brings to the ecosystem is intuitive and secure trading of tokens on the Scroll chain - which will empower more people to trade without fears and worries. ",
  },

  {
    id: 92,
    img: "../public/images/uPad.jpg",
    url: "https://upad.io/",

    twitter: "https://twitter.com/upad_io",
    discord: "https://discord.com/invite/upad",
    telegram: "https://t.me/uPad_io",
    title: "uPad",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "uPad is a DEX, is exclusively built on Scroll, offering unique visuals and an interface inspired by medieval merchants. Beyond its visual appeal, uPad incorporates a point program inspired by various sources, encouraging user engagement in trading and liquidity provision for our DEX. Through uPad's DEX products driving transactions for Scroll, it also includes a bridge that attracts capital to the ecosystem. With captivating visuals and a rewarding point program, uPad aims to cultivate a sustainable user base for the Scroll ecosystem ",
  },
  {
    id: 93,
    img: "../public/images/Parabol.jpg",
    url: "https://www.parabol.fi/",

    twitter: "https://twitter.com/parabolfi",

    telegram: "https://t.me/parabolfi",
    title: "Parabol",
    category: "DeFi",
    mainnet: true,
    labels: ["mainnet"],
    text: "Parabol is a high-yield stablecoin protocol for the global market. ",
  },
  {
    id: 94,
    img: "../public/images/PenPad.jpg",
    url: "https://penpad.io/home",
    github: "https://github.com/john-smilga",
    twitter: "https://twitter.com/pen_pad",
    discord: "https://discord.com/invite/v5nb2Q3Zt3",
    telegram: "https://t.me/penpad",
    title: "PenPad",
    category: "Community",
    mainnet: true,
    labels: ["mainnet"],
    text: "PenPad is the next-gen launch platform that provides fair, flexible and interactive Web3 project investment opportunities to all. ",
  },
  {
    id: 95,
    img: "../public/images/Micro3.jpg",
    url: "https://micro3.io/",

    twitter: "https://twitter.com/Micro3io",
    discord: "https://discord.com/invite/RZcFftRpT3",

    title: "Micro3",
    category: "Community",
    mainnet: true,
    labels: ["mainnet"],
    text: "Micro3 is a Decentralized SocialFi Mint-To-Earn platform, empowering Web3 projects and individuals through creator economy, utilized by LayerZero and Chainlink technologies. Users are rewarded through their NFT minting participation in both social and on-chain quests from Web3 projects. Micro3 also distributes revenue sharing and airdrops based on user’s history and contribution to the platform. Besides, projects and content creator can leverage on Micro3’s infrastructure to deploy their own NFTs and conveniently snapshot those eligible for airdrop across blockchains (NFT Infrastructure As-A-Services) ",
  },
  {
    id: 96,
    img: "../public/images/Retro.jpg",
    url: "https://retrobridge.io/",
    github: "https://github.com/retro-bridge",
    twitter: "https://twitter.com/retro_bridge",
    discord: "https://discord.com/invite/retrobridge",

    title: "Retro Bridge",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Instantly Bridge Anywhere with Lowest Fees",
  },
  {
    id: 97,
    img: "../public/images/Comparenodes.png",
    url: "https://www.comparenodes.com/",

    twitter: "https://twitter.com/CompareNodes",

    title: "Compare Nodes",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "We compute round-trip latencies from 27 locations on six continents in just three clicks and 30 seconds. ",
  },
  {
    id: 98,
    img: "../public/images/Automata.jpg",
    url: "https://www.ata.network/",
    github: "https://github.com/automata-network",
    twitter: "https://twitter.com/AutomataNetwork",
    discord: "https://discord.com/invite/automata",
    telegram: "https://t.me/ata_network",
    title: "Automata Network",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Modular attestation layer extending machine trust to Ethereum. ",
  },
  {
    id: 99,
    img: "../public/images/3cities.jpg",
    url: "https://3cities.xyz/",

    twitter: "https://twitter.com/3cities_xyz",
    discord: "https://discord.com",
    telegram: "https://t.me/+aMJE0gxJg9c2NWNh",
    title: "3cities",
    category: "Infrastructure",
    mainnet: true,
    labels: ["mainnet"],
    text: "Defragmenting L2 payments and building a decentralized payments protocol for all of Ethereum. ",
  },
];

export default projectsdata;
